-- AUTO-GENERATED by src/Gen/Program.fs -- do not edit by hand.
-- Full schema derived from src/Models/Domain.fs

CREATE TABLE guests (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    deleted_at INTEGER
);

CREATE TABLE identities (
    id TEXT PRIMARY KEY,
    guest_id TEXT NOT NULL,
    provider TEXT NOT NULL,
    provider_user_id TEXT NOT NULL,
    name TEXT NOT NULL,
    picture TEXT NOT NULL,
    email TEXT,
    activated_at INTEGER,
    created_at INTEGER NOT NULL,
    FOREIGN KEY (guest_id) REFERENCES guests(id)
);

CREATE TABLE articles_posts (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    teaser TEXT,
    body TEXT NOT NULL,
    image TEXT,
    article_date INTEGER NOT NULL,
    slug TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER,
    view_count INTEGER NOT NULL,
    deleted_at INTEGER
);

CREATE TABLE articles_comments (
    id TEXT PRIMARY KEY,
    post_id TEXT NOT NULL,
    identity_id TEXT NOT NULL,
    parent_id TEXT,
    author TEXT NOT NULL,
    content TEXT NOT NULL,
    removed INTEGER NOT NULL,
    created_at INTEGER NOT NULL,
    deleted_at INTEGER,
    FOREIGN KEY (post_id) REFERENCES articles_posts(id),
    FOREIGN KEY (identity_id) REFERENCES identities(id),
    FOREIGN KEY (parent_id) REFERENCES articles_comments(id)
);

-- Indexes
CREATE INDEX idx_guests_created_at ON guests(created_at DESC);
CREATE INDEX idx_identities_guest_id ON identities(guest_id);
CREATE INDEX idx_identities_created_at ON identities(created_at DESC);
CREATE INDEX idx_articles_posts_created_at ON articles_posts(created_at DESC);
CREATE INDEX idx_articles_comments_post_id ON articles_comments(post_id);
CREATE INDEX idx_articles_comments_identity_id ON articles_comments(identity_id);
CREATE INDEX idx_articles_comments_parent_id ON articles_comments(parent_id);
CREATE INDEX idx_articles_comments_created_at ON articles_comments(created_at DESC);
