-- AUTO-GENERATED by src/Gen/Program.fs -- do not edit by hand.
-- Full schema derived from src/Models/Domain.fs

CREATE TABLE guests (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    picture TEXT NOT NULL,
    session_id TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    deleted_at INTEGER
);

CREATE TABLE items (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    link TEXT,
    image TEXT,
    extract TEXT,
    owner_comment TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER,
    view_count INTEGER NOT NULL,
    deleted_at INTEGER
);

CREATE TABLE comments (
    id TEXT PRIMARY KEY,
    item_id TEXT NOT NULL,
    guest_id TEXT NOT NULL,
    parent_id TEXT,
    author TEXT NOT NULL,
    content TEXT NOT NULL,
    removed INTEGER NOT NULL,
    created_at INTEGER NOT NULL,
    deleted_at INTEGER,
    FOREIGN KEY (item_id) REFERENCES items(id),
    FOREIGN KEY (guest_id) REFERENCES guests(id)
);

CREATE TABLE tags (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    deleted_at INTEGER
);

CREATE TABLE item_tags (
    item_id TEXT NOT NULL,
    tag_id TEXT NOT NULL,
    deleted_at INTEGER,
    FOREIGN KEY (item_id) REFERENCES items(id),
    FOREIGN KEY (tag_id) REFERENCES tags(id)
);

CREATE TABLE guest_sessions (
    guest_id TEXT NOT NULL,
    display_name TEXT NOT NULL,
    created_at INTEGER NOT NULL
);

-- Indexes
CREATE INDEX idx_guests_created_at ON guests(created_at DESC);
CREATE INDEX idx_items_created_at ON items(created_at DESC);
CREATE INDEX idx_comments_item_id ON comments(item_id);
CREATE INDEX idx_comments_guest_id ON comments(guest_id);
CREATE INDEX idx_comments_created_at ON comments(created_at DESC);
CREATE INDEX idx_tags_created_at ON tags(created_at DESC);
CREATE INDEX idx_item_tags_item_id ON item_tags(item_id);
CREATE INDEX idx_item_tags_tag_id ON item_tags(tag_id);
