-- AUTO-GENERATED by src/Gen/Program.fs -- do not edit by hand.
-- Full schema derived from src/Models/Domain.fs

CREATE TABLE plants (
    id TEXT PRIMARY KEY,
    slug TEXT NOT NULL,
    scientific_name TEXT NOT NULL,
    common_names TEXT NOT NULL,
    family TEXT NOT NULL,
    genus TEXT NOT NULL,
    aliases TEXT NOT NULL,
    forms TEXT NOT NULL,
    height TEXT NOT NULL,
    sun TEXT NOT NULL,
    water TEXT NOT NULL,
    garden_features TEXT NOT NULL,
    wildlife TEXT NOT NULL,
    habit TEXT NOT NULL,
    bark TEXT NOT NULL,
    leaves TEXT NOT NULL,
    phyllodes TEXT NOT NULL,
    flowers TEXT NOT NULL,
    fruit TEXT NOT NULL,
    flowering TEXT NOT NULL,
    fruiting TEXT NOT NULL,
    features TEXT NOT NULL,
    habitat TEXT NOT NULL,
    cultivation TEXT NOT NULL,
    traditional_uses TEXT NOT NULL,
    notes TEXT NOT NULL,
    distribution TEXT NOT NULL,
    source_references TEXT NOT NULL,
    source_evidence TEXT NOT NULL,
    endemic_nt INTEGER NOT NULL,
    published INTEGER NOT NULL,
    sort_order INTEGER NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER,
    deleted_at INTEGER
);

CREATE TABLE plant_photos (
    id TEXT PRIMARY KEY,
    plant_id TEXT NOT NULL,
    image TEXT NOT NULL,
    thumbnail TEXT NOT NULL,
    caption TEXT NOT NULL,
    photographer TEXT NOT NULL,
    sort_order INTEGER NOT NULL,
    published INTEGER NOT NULL,
    source_evidence TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER,
    deleted_at INTEGER,
    FOREIGN KEY (plant_id) REFERENCES plants(id)
);

-- Indexes
CREATE UNIQUE INDEX idx_plants_slug ON plants(slug);
CREATE INDEX idx_plants_created_at ON plants(created_at DESC);
CREATE INDEX idx_plant_photos_plant_id ON plant_photos(plant_id);
CREATE INDEX idx_plant_photos_created_at ON plant_photos(created_at DESC);
