-- AUTO-GENERATED by src/Gen/Program.fs -- do not edit by hand.
-- Full schema derived from src/Models/Domain.fs

CREATE TABLE pages (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    title TEXT NOT NULL,
    teaser TEXT NOT NULL,
    body TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER,
    deleted_at INTEGER
);

CREATE TABLE menu_items (
    id TEXT PRIMARY KEY,
    item TEXT NOT NULL,
    title TEXT NOT NULL,
    link TEXT NOT NULL,
    parent_item TEXT NOT NULL,
    ordinal INTEGER NOT NULL,
    created_at INTEGER NOT NULL,
    deleted_at INTEGER
);

-- Indexes
CREATE INDEX idx_pages_created_at ON pages(created_at DESC);
CREATE INDEX idx_menu_items_created_at ON menu_items(created_at DESC);
