-- AUTO-GENERATED by src/Gen/Program.fs -- do not edit by hand.
-- Full schema derived from src/Models/Domain.fs

CREATE TABLE albums (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT NOT NULL,
    cover TEXT,
    release_date INTEGER NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER,
    deleted_at INTEGER
);

CREATE TABLE tracks (
    id TEXT PRIMARY KEY,
    album_id TEXT NOT NULL,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    track_index INTEGER NOT NULL,
    plays INTEGER NOT NULL,
    created_at INTEGER NOT NULL,
    deleted_at INTEGER,
    FOREIGN KEY (album_id) REFERENCES albums(id)
);

-- Indexes
CREATE INDEX idx_albums_created_at ON albums(created_at DESC);
CREATE INDEX idx_tracks_album_id ON tracks(album_id);
CREATE INDEX idx_tracks_created_at ON tracks(created_at DESC);
