-- AUTO-GENERATED by src/Gen/Program.fs -- do not edit by hand.
-- Full schema derived from src/Models/Domain.fs

CREATE TABLE guests (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    deleted_at INTEGER
);

CREATE TABLE identities (
    id TEXT PRIMARY KEY,
    guest_id TEXT NOT NULL,
    provider TEXT NOT NULL,
    provider_user_id TEXT NOT NULL,
    name TEXT NOT NULL,
    picture TEXT NOT NULL,
    email TEXT,
    activated_at INTEGER,
    created_at INTEGER NOT NULL,
    FOREIGN KEY (guest_id) REFERENCES guests(id)
);

CREATE TABLE items (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    link TEXT,
    image TEXT,
    extract TEXT,
    owner_comment TEXT NOT NULL,
    slug TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER,
    view_count INTEGER NOT NULL,
    origin_entry_key TEXT,
    deleted_at INTEGER
);

CREATE TABLE comments (
    id TEXT PRIMARY KEY,
    item_id TEXT NOT NULL,
    identity_id TEXT NOT NULL,
    parent_id TEXT,
    author TEXT NOT NULL,
    content TEXT NOT NULL,
    removed INTEGER NOT NULL,
    created_at INTEGER NOT NULL,
    deleted_at INTEGER,
    FOREIGN KEY (item_id) REFERENCES items(id),
    FOREIGN KEY (identity_id) REFERENCES identities(id)
);

CREATE TABLE tags (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    deleted_at INTEGER
);

CREATE TABLE item_tags (
    item_id TEXT NOT NULL,
    tag_id TEXT NOT NULL,
    deleted_at INTEGER,
    FOREIGN KEY (item_id) REFERENCES items(id),
    FOREIGN KEY (tag_id) REFERENCES tags(id)
);

CREATE TABLE alert_sources (
    id TEXT PRIMARY KEY,
    topic TEXT NOT NULL,
    feed_url TEXT NOT NULL,
    enabled INTEGER NOT NULL,
    created_at INTEGER NOT NULL
);

CREATE TABLE pending_posts (
    id TEXT PRIMARY KEY,
    source_id TEXT NOT NULL,
    entry_key TEXT NOT NULL,
    title TEXT NOT NULL,
    link TEXT NOT NULL,
    snippet TEXT NOT NULL,
    published_at INTEGER NOT NULL,
    approved INTEGER NOT NULL,
    rejected INTEGER NOT NULL,
    owner_comment TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    FOREIGN KEY (source_id) REFERENCES alert_sources(id)
);

-- Indexes
CREATE INDEX idx_guests_created_at ON guests(created_at DESC);
CREATE INDEX idx_identities_guest_id ON identities(guest_id);
CREATE INDEX idx_identities_created_at ON identities(created_at DESC);
CREATE UNIQUE INDEX idx_items_origin_entry_key ON items(origin_entry_key);
CREATE INDEX idx_items_created_at ON items(created_at DESC);
CREATE INDEX idx_comments_item_id ON comments(item_id);
CREATE INDEX idx_comments_identity_id ON comments(identity_id);
CREATE INDEX idx_comments_created_at ON comments(created_at DESC);
CREATE UNIQUE INDEX idx_tags_name ON tags(name);
CREATE INDEX idx_tags_created_at ON tags(created_at DESC);
CREATE INDEX idx_item_tags_item_id ON item_tags(item_id);
CREATE INDEX idx_item_tags_tag_id ON item_tags(tag_id);
CREATE UNIQUE INDEX idx_alert_sources_feed_url ON alert_sources(feed_url);
CREATE INDEX idx_alert_sources_created_at ON alert_sources(created_at DESC);
CREATE INDEX idx_pending_posts_source_id ON pending_posts(source_id);
CREATE UNIQUE INDEX idx_pending_posts_entry_key ON pending_posts(entry_key);
CREATE INDEX idx_pending_posts_created_at ON pending_posts(created_at DESC);
