-- AUTO-GENERATED by src/Gen/Program.fs -- do not edit by hand.
-- Full schema derived from src/Models/Domain.fs

CREATE TABLE guests (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    deleted_at INTEGER
);

CREATE TABLE identities (
    id TEXT PRIMARY KEY,
    guest_id TEXT NOT NULL,
    provider TEXT NOT NULL,
    provider_user_id TEXT NOT NULL,
    name TEXT NOT NULL,
    picture TEXT NOT NULL,
    email TEXT,
    activated_at INTEGER,
    created_at INTEGER NOT NULL,
    FOREIGN KEY (guest_id) REFERENCES guests(id)
);

CREATE TABLE blog_items (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    link TEXT,
    image TEXT,
    extract TEXT,
    owner_comment TEXT NOT NULL,
    article_date INTEGER NOT NULL,
    slug TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER,
    view_count INTEGER NOT NULL,
    deleted_at INTEGER
);

CREATE TABLE blog_comments (
    id TEXT PRIMARY KEY,
    item_id TEXT NOT NULL,
    identity_id TEXT NOT NULL,
    parent_id TEXT,
    author TEXT NOT NULL,
    content TEXT NOT NULL,
    removed INTEGER NOT NULL,
    created_at INTEGER NOT NULL,
    deleted_at INTEGER,
    FOREIGN KEY (item_id) REFERENCES blog_items(id),
    FOREIGN KEY (identity_id) REFERENCES identities(id),
    FOREIGN KEY (parent_id) REFERENCES blog_comments(id)
);

CREATE TABLE blog_tags (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    deleted_at INTEGER
);

CREATE TABLE blog_item_tags (
    id TEXT PRIMARY KEY,
    item_id TEXT NOT NULL,
    tag_id TEXT NOT NULL,
    deleted_at INTEGER,
    FOREIGN KEY (item_id) REFERENCES blog_items(id),
    FOREIGN KEY (tag_id) REFERENCES blog_tags(id)
);

CREATE TABLE blog_snapshots (
    id TEXT PRIMARY KEY,
    item_id TEXT NOT NULL,
    kind TEXT NOT NULL,
    blob_key TEXT NOT NULL,
    source_url TEXT NOT NULL,
    status TEXT NOT NULL,
    error TEXT,
    created_at INTEGER NOT NULL,
    deleted_at INTEGER,
    FOREIGN KEY (item_id) REFERENCES blog_items(id)
);

CREATE TABLE alerts_alert_sources (
    id TEXT PRIMARY KEY,
    topic TEXT NOT NULL,
    feed_url TEXT NOT NULL,
    enabled INTEGER NOT NULL,
    created_at INTEGER NOT NULL
);

CREATE TABLE alerts_pending_posts (
    id TEXT PRIMARY KEY,
    source_id TEXT NOT NULL,
    entry_key TEXT NOT NULL,
    title TEXT NOT NULL,
    link TEXT NOT NULL,
    snippet TEXT NOT NULL,
    published_at INTEGER NOT NULL,
    approved INTEGER NOT NULL,
    rejected INTEGER NOT NULL,
    owner_comment TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    FOREIGN KEY (source_id) REFERENCES alerts_alert_sources(id)
);

CREATE TABLE alerts_promotions (
    id TEXT PRIMARY KEY,
    entry_key TEXT NOT NULL,
    item_id TEXT NOT NULL,
    created_at INTEGER NOT NULL
);

-- Indexes
CREATE INDEX idx_guests_created_at ON guests(created_at DESC);
CREATE INDEX idx_identities_guest_id ON identities(guest_id);
CREATE INDEX idx_identities_created_at ON identities(created_at DESC);
CREATE UNIQUE INDEX idx_blog_items_slug ON blog_items(slug);
CREATE INDEX idx_blog_items_created_at ON blog_items(created_at DESC);
CREATE INDEX idx_blog_comments_item_id ON blog_comments(item_id);
CREATE INDEX idx_blog_comments_identity_id ON blog_comments(identity_id);
CREATE INDEX idx_blog_comments_parent_id ON blog_comments(parent_id);
CREATE INDEX idx_blog_comments_created_at ON blog_comments(created_at DESC);
CREATE UNIQUE INDEX idx_blog_tags_name ON blog_tags(name);
CREATE INDEX idx_blog_tags_created_at ON blog_tags(created_at DESC);
CREATE INDEX idx_blog_item_tags_item_id ON blog_item_tags(item_id);
CREATE INDEX idx_blog_item_tags_tag_id ON blog_item_tags(tag_id);
CREATE INDEX idx_blog_snapshots_item_id ON blog_snapshots(item_id);
CREATE INDEX idx_blog_snapshots_created_at ON blog_snapshots(created_at DESC);
CREATE UNIQUE INDEX idx_alerts_alert_sources_feed_url ON alerts_alert_sources(feed_url);
CREATE INDEX idx_alerts_alert_sources_created_at ON alerts_alert_sources(created_at DESC);
CREATE INDEX idx_alerts_pending_posts_source_id ON alerts_pending_posts(source_id);
CREATE UNIQUE INDEX idx_alerts_pending_posts_entry_key ON alerts_pending_posts(entry_key);
CREATE INDEX idx_alerts_pending_posts_created_at ON alerts_pending_posts(created_at DESC);
CREATE UNIQUE INDEX idx_alerts_promotions_entry_key ON alerts_promotions(entry_key);
CREATE INDEX idx_alerts_promotions_created_at ON alerts_promotions(created_at DESC);
