-- AUTO-GENERATED by src/Gen/Program.fs -- do not edit by hand.
-- Full schema derived from src/Models/Domain.fs

CREATE TABLE articles (
    id TEXT PRIMARY KEY,
    aid INTEGER NOT NULL,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    section TEXT NOT NULL,
    article_date INTEGER NOT NULL,
    attrib TEXT NOT NULL,
    source TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER,
    view_count INTEGER NOT NULL,
    deleted_at INTEGER
);

-- Indexes
CREATE INDEX idx_articles_created_at ON articles(created_at DESC);
